[build]
  command = "npm install && npm run build"
  functions = "functions"

[functions]
  included_files = ["assets/*","sitemap/*","*","./arc-sw.js"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/core/:splat"
  status = 200
  force = true

[[redirects]]
  from = "./arc-sw.js"
  to = "https://arc.io/arc-sw.js"
  status = 200
  force = true
